name: Format and Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  format_and_lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: |
          gem install rubocop
          npm install -g prettier

      - name: Format Markdown files
        run: |
          find . -name "*.md" -exec prettier --write {} \;

      - name: Run Rubocop
        run: rubocop -A

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "Format Markdown files and run Rubocop"
          git push origin main
